version: '3.7'
services:
  es-test:
    build:
      context: .
    image: es-test:latest
    env_file:
      - .env
    volumes:
      - ./test-es.py:/test-es.py
    # ports:
    #   - 5090:5090
#     networks:
#       - esnet
#     depends_on:
#       - es
#   es:
#     image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
#     environment:
#       - node.max_local_storage_nodes=1
#       - ES_HOST=http://localhost:9200
#       - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#     volumes:
#       - esdata:/usr/share/elasticsearch/data
#     networks:
#       - esnet
#     ports:
#       - "9200:9200"
#     deploy:
#       mode: 'replicated'
#       replicas: 1
#       resources:
#         limits:
#           memory: 1g
#     ulimits:
#       memlock:
#         soft: -1
#         hard: -1

# networks:
#   esnet:
# volumes:
#   esdata:
#     driver: local
